export const icons = {
  yback: require("./y-back-button-icon.png"),
  gback: require("./g-back-button-icon.png"),
  blackboard: require("./blackboard-icon.png"),
  createCard: require("./create-card-icon.png"),
  edit: require("./edit-icon.png"),
  erase: require("./erase-icon.png"),
  google: require("./google-logo-icon.png"),
  key: require("./key-icon.png"),
  manageReport: require("./manage-report-icon.png"),
  menu: require("./menu-icon.png"),
  play: require("./play-icon.png"),
  recordAudio: require("./record-audio-icon.png"),
  report: require("./report-icon.png"),
  requestConfirm: require("./request-confirm-icon.png"),
  searchPic: require("./search-pic-icon.png"),
  trash: require("./trash-icon.png"),
  uploadGallery: require("./upload-gallery-icon.png"),
}